/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDrYMoMtKH04bgcs2HLLXPqg",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        sslCert: secret("CUSTOM_SSL_CERT")
    }
}).schema({
    "authors": a.model({
        id: a.string().required(),
        name: a.string().required(),
        link: a.string().required(),
        bio: a.string().required(),
        description: a.string().required()
    }).identifier([
        "id"
    ]),
    "quotes": a.model({
        id: a.string().required(),
        content: a.string().required(),
        author: a.string().required()
    }).identifier([
        "id"
    ]),
    "quotes_tags": a.model({
        quote_id: a.string().required(),
        tag_id: a.string().required()
    }).identifier([
        "quote_id",
        "tag_id"
    ]),
    "tags": a.model({
        id: a.string().required(),
        name: a.string().required()
    }).identifier([
        "id"
    ])
});
